apiVersion: apps/v1
kind: Deployment
metadata:
  name: daml-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daml-sandbox
  template:
    metadata:
      labels:
        app: daml-sandbox
    spec:
      containers:
      - image: shleger/daml-sandbox:latest
        name: daml-sandbox

---

apiVersion: v1
kind: Service
metadata:
  name: daml-sandbox
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "daml-sandbox"
    port: 6865
  selector:
    app: hello-world
