apiVersion: apps/v1
kind: Deployment
metadata:
  name: daml-sdk-cut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daml-sdk-cut
  template:
    metadata:
      labels:
        app: daml-sdk-cut
    spec:
      containers:
      - image: okteto.dev/daml-sdk-cut
        name: daml-sdk-cut

---

# nodePort: The port on the node where external traffic will come in on
# port: The port of this service
# targetPort The target port on the pod(s) to forward traffic to
# Also worth noting that if targetPort is not set, it will default to the same value as port.

apiVersion: v1
kind: Service
metadata:
  name: daml-sdk-cut
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "sandbox"
    port: 6865
  selector:
    app: daml-sdk-cut
